import { TRPCError } from "@trpc/server";
import { and, eq } from "drizzle-orm";
import { z } from "zod";
import { bankAccounts, bankTransactions } from "../drizzle/schema";
import { approveBankTransaction, approveJournalEntry, createJournalEntry, getDb, upsertBookingRule } from "./db";
import { assertSupportedAccountingCurrency } from "./accountingCurrency";
import { toDateStr } from "./accountingDate";
import { logger } from "./_core/logger";
import { orgProcedure } from "./_core/trpc";

const standard = z.object({ transactionId: z.number(), debitAccountId: z.number(), creditAccountId: z.number(), description: z.string().optional() });
const collective = z.object({ transactionId: z.number(), description: z.string().min(1), lines: z.array(z.object({ accountId: z.number(), side: z.enum(["debit", "credit"]), amount: z.string(), description: z.string().optional(), vatRate: z.string().optional() })).min(2) });
export const bankImportApprovalProcedures = {
  approveTransaction: orgProcedure.input(standard).mutation(async ({ input, ctx }) => { if (!ctx.user?.id) throw new TRPCError({ code: "UNAUTHORIZED" }); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const [tx] = await db.select().from(bankTransactions).where(and(eq(bankTransactions.id, input.transactionId), eq(bankTransactions.organizationId, ctx.organizationId))).limit(1); if (!tx) throw new TRPCError({ code: "NOT_FOUND" }); try { assertSupportedAccountingCurrency(tx.currency); } catch (error) { throw new TRPCError({ code: "BAD_REQUEST", message: error instanceof Error ? error.message : "Fremdwährung kann nicht verbucht werden." }); } const amount = Math.abs(parseFloat(tx.amount)); const entryId = await createJournalEntry({ organizationId: ctx.organizationId, bookingDate: toDateStr(tx.transactionDate)!, valueDate: toDateStr(tx.valueDate), description: input.description ?? tx.description ?? "Bankbuchung", source: "bank_import", sourceRef: `bank-tx-${tx.id}`, fiscalYear: new Date(tx.transactionDate).getFullYear(), status: "approved", lines: [{ accountId: input.debitAccountId, side: "debit", amount: amount.toFixed(2) }, { accountId: input.creditAccountId, side: "credit", amount: amount.toFixed(2) }] }); await approveBankTransaction(tx.id, entryId); await approveJournalEntry(entryId, ctx.user.id); if (tx.counterparty) try { const ids = (await db.select({ accountId: bankAccounts.accountId }).from(bankAccounts).where(eq(bankAccounts.organizationId, ctx.organizationId))).map(a => a.accountId); const rule: Parameters<typeof upsertBookingRule>[0] = { organizationId: ctx.organizationId, counterpartyPattern: tx.counterparty.trim(), bookingTextTemplate: input.description ?? tx.description ?? undefined }; if (!ids.includes(input.debitAccountId)) rule.debitAccountId = input.debitAccountId; if (!ids.includes(input.creditAccountId)) rule.creditAccountId = input.creditAccountId; await upsertBookingRule(rule); } catch (err) { logger.error({ err, transactionId: tx.id }, "Failed to learn booking rule from approved transaction"); } return { success: true, entryId }; }),
  approveCollectiveTransaction: orgProcedure.input(collective).mutation(async ({ input, ctx }) => { if (!ctx.user?.id) throw new TRPCError({ code: "UNAUTHORIZED" }); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const [tx] = await db.select().from(bankTransactions).where(and(eq(bankTransactions.id, input.transactionId), eq(bankTransactions.organizationId, ctx.organizationId))).limit(1); if (!tx) throw new TRPCError({ code: "NOT_FOUND" }); const entryId = await createJournalEntry({ organizationId: ctx.organizationId, bookingDate: toDateStr(tx.transactionDate)!, valueDate: toDateStr(tx.valueDate), description: input.description, source: "bank_import", sourceRef: `bank-tx-${tx.id}`, fiscalYear: new Date(tx.transactionDate).getFullYear(), status: "approved", lines: input.lines }); await approveBankTransaction(tx.id, entryId); await approveJournalEntry(entryId, ctx.user.id); return { success: true, entryId }; }),
  bulkApprove: orgProcedure.input(z.object({ transactions: z.array(standard) })).mutation(async ({ input, ctx }) => { if (!ctx.user?.id) throw new TRPCError({ code: "UNAUTHORIZED" }); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const bankAccountIds = (await db.select({ accountId: bankAccounts.accountId }).from(bankAccounts).where(eq(bankAccounts.organizationId, ctx.organizationId))).map(bank => bank.accountId); const results: Array<{ txId: number; success: boolean; entryId?: number; error?: string }> = []; for (const item of input.transactions) try { const [tx] = await db.select().from(bankTransactions).where(and(eq(bankTransactions.id, item.transactionId), eq(bankTransactions.organizationId, ctx.organizationId))).limit(1); if (!tx || tx.status !== "pending") { results.push({ txId: item.transactionId, success: false, error: "Nicht ausstehend" }); continue; } assertSupportedAccountingCurrency(tx.currency); const amount = Math.abs(parseFloat(tx.amount)); const entryId = await createJournalEntry({ organizationId: ctx.organizationId, bookingDate: toDateStr(tx.transactionDate)!, valueDate: toDateStr(tx.valueDate), description: item.description ?? tx.description ?? "Bankbuchung", source: "bank_import", sourceRef: `bank-tx-${tx.id}`, fiscalYear: new Date(tx.transactionDate).getFullYear(), status: "approved", lines: [{ accountId: item.debitAccountId, side: "debit", amount: amount.toFixed(2) }, { accountId: item.creditAccountId, side: "credit", amount: amount.toFixed(2) }] }); await approveBankTransaction(tx.id, entryId); await approveJournalEntry(entryId, ctx.user.id); if (tx.counterparty) { const rule: Parameters<typeof upsertBookingRule>[0] = { organizationId: ctx.organizationId, counterpartyPattern: tx.counterparty.trim(), bookingTextTemplate: item.description ?? tx.description ?? undefined }; if (!bankAccountIds.includes(item.debitAccountId)) rule.debitAccountId = item.debitAccountId; if (!bankAccountIds.includes(item.creditAccountId)) rule.creditAccountId = item.creditAccountId; await upsertBookingRule(rule); } results.push({ txId: item.transactionId, success: true, entryId }); } catch (error) { results.push({ txId: item.transactionId, success: false, error: error instanceof Error ? error.message : "Fehler" }); } const approved = results.filter(result => result.success).length; return { results, approved, failed: results.length - approved }; }),
};
