import { TRPCError } from "@trpc/server";
import { and, eq, inArray } from "drizzle-orm";
import { z } from "zod";
import { bankAccounts, bankTransactions, companySettings } from "../drizzle/schema";
import { getAllAccounts, getAllBookingRules, getDb } from "./db";
import { invokeLLM } from "./_core/llm";
import { logger } from "./_core/logger";
import { orgProcedure } from "./_core/trpc";
import { bankImportBookingSuggestionSchema } from "./bankImportAiSchemas";

export const bankImportCategorizationProcedures = { categorizeWithAI: orgProcedure.input(z.object({ transactionIds: z.array(z.number()) })).mutation(async ({ input, ctx }) => {
  if (!ctx.user?.id) throw new TRPCError({ code: "UNAUTHORIZED" }); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });
  const [org] = await db.select({ name: companySettings.companyName }).from(companySettings).where(eq(companySettings.organizationId, ctx.organizationId)).limit(1); const accounts = await getAllAccounts(ctx.organizationId); const rules = await getAllBookingRules(ctx.organizationId); const map = new Map(accounts.map(a => [a.id, a]));
  const accountList = accounts.map(a => `${a.number}: ${a.name} (${a.accountType})`).join("\n"); const rulesText = rules.slice(0, 40).map(r => `- ${r.counterpartyPattern} → Soll ${r.debitAccountId ? map.get(r.debitAccountId)?.number ?? "?" : "?"} / Haben ${r.creditAccountId ? map.get(r.creditAccountId)?.number ?? "?" : "?"}`).join("\n");
  const txs = await db.select().from(bankTransactions).where(and(eq(bankTransactions.organizationId, ctx.organizationId), inArray(bankTransactions.id, input.transactionIds))); const banks = new Map((await db.select({ id: bankAccounts.id, accountId: bankAccounts.accountId }).from(bankAccounts).where(eq(bankAccounts.organizationId, ctx.organizationId))).map(b => [b.id, b])); const results: Array<{ txId: number; success: boolean; confidence?: number }> = [];
  for (const tx of txs) try { const own = banks.get(tx.bankAccountId); const bankNumber = own ? accounts.find(a => a.id === own.accountId)?.number ?? "" : ""; const prompt = `Du bist ein Schweizer Buchhalter für ${org?.name ?? "Ihre Firma"}. Antworte NUR mit JSON {"debitAccountNumber":"XXXX","creditAccountNumber":"XXXX","confidence":0,"reasoning":"kurz"}. Transaktion: ${tx.transactionDate}; CHF ${tx.amount}; ${tx.description}; Gegenpartei ${tx.counterparty ?? "unbekannt"}; Bankkonto ${bankNumber}. Kontenplan:\n${accountList}\nRegeln:\n${rulesText}`; const response = await invokeLLM({ messages: [{ role: "user", content: prompt }], response_format: { type: "json_schema", json_schema: { name: "booking_suggestion", strict: true, schema: { type: "object", properties: { debitAccountNumber: { type: "string" }, creditAccountNumber: { type: "string" }, confidence: { type: "integer" }, reasoning: { type: "string" } }, required: ["debitAccountNumber", "creditAccountNumber", "confidence", "reasoning"], additionalProperties: false } } } }); const raw = response.choices[0]?.message?.content; if (typeof raw !== "string") throw new Error("Keine KI-Antwort"); const suggestion = bankImportBookingSuggestionSchema.parse(JSON.parse(raw)); const debit = accounts.find(a => a.number === suggestion.debitAccountNumber); const credit = accounts.find(a => a.number === suggestion.creditAccountNumber); if (!debit || !credit) throw new Error("Ungültige Kontenzuordnung"); await db.update(bankTransactions).set({ suggestedDebitAccountId: debit.id, suggestedCreditAccountId: credit.id, aiConfidence: suggestion.confidence, aiReasoning: suggestion.reasoning }).where(and(eq(bankTransactions.id, tx.id), eq(bankTransactions.organizationId, ctx.organizationId))); results.push({ txId: tx.id, success: true, confidence: suggestion.confidence }); } catch (err) { logger.error({ err, transactionId: tx.id }, "AI transaction categorization failed"); results.push({ txId: tx.id, success: false }); }
  return { results };
}) };
