import { TRPCError } from "@trpc/server";
import { and, eq, sql } from "drizzle-orm";
import crypto from "crypto";
import { z } from "zod";
import { bankAccounts, bankTransactions, documents, importHistory } from "../drizzle/schema";
import { calculateMatchScore, getDb, saveBankTransaction } from "./db";
import { orgProcedure } from "./_core/trpc";
import { logger } from "./_core/logger";
import { normaliseDate } from "../shared/bankParser";
import { bankImportDocumentMatchMetadataSchema } from "./bankImportAiSchemas";

const inputSchema = z.object({ bankAccountId: z.number(), transactions: z.array(z.object({ transactionDate: z.string(), valueDate: z.string().nullable().optional(), amount: z.string(), currency: z.string().default("CHF"), description: z.string(), reference: z.string().nullable().optional(), counterparty: z.string().nullable().optional(), counterpartyIban: z.string().nullable().optional() })), importBatchId: z.string().optional(), filename: z.string().optional(), fileType: z.string().optional(), s3Key: z.string().optional(), s3Url: z.string().optional() });

export const bankImportIngestionProcedures = { importTransactions: orgProcedure.input(inputSchema).mutation(async ({ input, ctx }) => {
  if (!ctx.user?.id) throw new TRPCError({ code: "UNAUTHORIZED" }); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });
  const [account] = await db.select({ id: bankAccounts.id }).from(bankAccounts).where(and(eq(bankAccounts.id, input.bankAccountId), eq(bankAccounts.organizationId, ctx.organizationId))); if (!account) throw new TRPCError({ code: "FORBIDDEN", message: "Bankkonto gehört nicht zur aktiven Organisation" });
  const batchId = input.importBatchId ?? `import-${Date.now()}`; let imported = 0, duplicates = 0, skipped = 0; let dateMin: string | null = null, dateMax: string | null = null;
  for (const tx of input.transactions) { const date = normaliseDate(tx.transactionDate); if (!date) { skipped++; continue; } if (dateMin === null || date.localeCompare(dateMin) < 0) dateMin = date; if (dateMax === null || date.localeCompare(dateMax) > 0) dateMax = date; const saved = await saveBankTransaction({ organizationId: ctx.organizationId, bankAccountId: input.bankAccountId, transactionDate: date, valueDate: tx.valueDate ? normaliseDate(tx.valueDate) ?? undefined : undefined, amount: tx.amount, currency: tx.currency, description: tx.description, reference: tx.reference ?? undefined, counterparty: tx.counterparty ?? undefined, counterpartyIban: tx.counterpartyIban ?? undefined, importBatchId: batchId, status: "pending", txHash: crypto.createHash("sha256").update(`${input.bankAccountId}-${date}-${tx.amount}-${tx.description}`).digest("hex") }); if (saved) imported++; else duplicates++; }
  if (input.filename) await db.insert(importHistory).values({ organizationId: ctx.organizationId, bankAccountId: input.bankAccountId, filename: input.filename, fileType: input.fileType ?? "unknown", s3Key: input.s3Key ?? null, s3Url: input.s3Url ?? null, importBatchId: batchId, transactionsTotal: input.transactions.length, transactionsImported: imported, transactionsDuplicate: duplicates, transactionsSkipped: skipped, dateRangeFrom: dateMin, dateRangeTo: dateMax, importedBy: ctx.user.openId }).catch(err => logger.error({ err, importBatchId: batchId }, "Failed to save bank import history"));
  let autoMatched = 0; if (imported) try { const txs = await db.select().from(bankTransactions).where(and(eq(bankTransactions.organizationId, ctx.organizationId), eq(bankTransactions.importBatchId, batchId), eq(bankTransactions.status, "pending"))); const docs = await db.select().from(documents).where(and(eq(documents.organizationId, ctx.organizationId), sql`${documents.aiMetadata} IS NOT NULL`, sql`${documents.matchStatus} IN ('pain001','unmatched')`)); for (const tx of txs) { if (parseFloat(tx.amount) >= 0) continue; let best: { id: number; score: number } | null = null; for (const doc of docs) try { const meta = bankImportDocumentMatchMetadataSchema.parse(JSON.parse(doc.aiMetadata || "{}")); const score = calculateMatchScore({ totalAmount: meta.totalAmount, counterparty: meta.counterparty, documentDate: meta.documentDate, counterpartyIban: meta.counterpartyIban, referenceNumber: meta.referenceNumber }, { amount: tx.amount, counterparty: tx.counterparty, transactionDate: tx.transactionDate, counterpartyIban: tx.counterpartyIban, reference: tx.reference }); if (score >= 60 && (!best || score > best.score)) best = { id: doc.id, score }; } catch {} if (best) { await db.update(documents).set({ bankTransactionId: tx.id, matchStatus: "matched", matchScore: best.score }).where(and(eq(documents.id, best.id), eq(documents.organizationId, ctx.organizationId))); await db.update(bankTransactions).set({ matchedDocumentId: best.id, matchScore: best.score }).where(and(eq(bankTransactions.id, tx.id), eq(bankTransactions.organizationId, ctx.organizationId))); autoMatched++; docs.splice(docs.findIndex(doc => doc.id === best!.id), 1); } } } catch (err) { logger.error({ err, importBatchId: batchId }, "Auto-match after bank import failed"); }
  return { imported, duplicates, skipped, batchId, autoMatched };
}) };
