import { TRPCError } from "@trpc/server";
import { and, asc, eq } from "drizzle-orm";
import { z } from "zod";
import { bankAccounts, bankTransactions, documents } from "../drizzle/schema";
import { getAllBookingRules, getDb, incrementRuleUsage } from "./db";
import { orgProcedure } from "./_core/trpc";

export const bankImportRefreshProcedures = { refreshSuggestions: orgProcedure.input(z.object({ bankAccountId: z.number().optional() })).mutation(async ({ input, ctx }) => {
  if (!ctx.user?.id) throw new TRPCError({ code: "UNAUTHORIZED" }); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const rules = await getAllBookingRules(ctx.organizationId); if (!rules.length) return { updated: 0, skippedManual: 0, total: 0, message: "Keine gelernten Regeln vorhanden. Verbuchen Sie zuerst einige Transaktionen manuell." };
  const banks = await db.select({ id: bankAccounts.id, accountId: bankAccounts.accountId }).from(bankAccounts).where(eq(bankAccounts.organizationId, ctx.organizationId)); const conditions = [eq(bankTransactions.organizationId, ctx.organizationId), eq(bankTransactions.status, "pending")]; if (input.bankAccountId) conditions.push(eq(bankTransactions.bankAccountId, input.bankAccountId)); const pending = await db.select().from(bankTransactions).where(and(...conditions)).orderBy(asc(bankTransactions.transactionDate)); let updated = 0, skippedManual = 0;
  for (const tx of pending) { if (tx.manuallyEdited) { skippedManual++; continue; } const name = (tx.counterparty ?? "").toLowerCase(); const rule = rules.find(r => name.includes(r.counterpartyPattern.toLowerCase())); if (!rule) continue; const data: Record<string, unknown> = {}; let changed = false; if (rule.debitAccountId) { data.suggestedDebitAccountId = rule.debitAccountId; changed = true; } if (rule.creditAccountId) { data.suggestedCreditAccountId = rule.creditAccountId; changed = true; } const own = banks.find(b => b.id === tx.bankAccountId)?.accountId; if (own) { if (parseFloat(tx.amount) < 0 && !data.suggestedCreditAccountId) { data.suggestedCreditAccountId = own; changed = true; } else if (parseFloat(tx.amount) >= 0 && !data.suggestedDebitAccountId) { data.suggestedDebitAccountId = own; changed = true; } } if (rule.bookingTextTemplate) { const date = new Date(tx.transactionDate); const months = ["Januar","Februar","März","April","Mai","Juni","Juli","August","September","Oktober","November","Dezember"]; const month = months[date.getMonth()] ?? ""; const year = date.getFullYear(); const quarter = `${Math.ceil((date.getMonth() + 1) / 3)}. Quartal`; let text = rule.bookingTextTemplate.replace(/(Januar|Februar|März|April|Mai|Juni|Juli|August|September|Oktober|November|Dezember)\s+\d{4}/g, `${month} ${year}`).replace(/\d+\.\s*Quartal\s+\d{4}/g, `${quarter} ${year}`).replace(/\{month\}/g, month).replace(/\{year\}/g, String(year)).replace(/\{quarter\}/g, quarter).replace(/\{counterparty\}/g, tx.counterparty ?? ""); if (text.includes("{customer}") && tx.matchedDocumentId) { const [doc] = await db.select().from(documents).where(and(eq(documents.organizationId, ctx.organizationId), eq(documents.id, tx.matchedDocumentId))).limit(1); const customer = doc?.filename.match(/\s([A-Za-zÀ-ɏ]+\s[A-Za-zÀ-ɏ]+)\.(pdf|jpg|png)$/i)?.[1]?.trim() ?? ""; text = text.replace(/\{customer\}/g, customer); } data.description = text; changed = true; } if (changed) { data.aiReasoning = `Gelernte Regel: ${rule.counterpartyPattern} (${rule.usageCount}x verwendet)`; data.aiConfidence = 98; await db.update(bankTransactions).set(data).where(and(eq(bankTransactions.id, tx.id), eq(bankTransactions.organizationId, ctx.organizationId))); await incrementRuleUsage(rule.id); updated++; } }
  const parts = [`${updated} von ${pending.length} Transaktionen aktualisiert`]; if (skippedManual) parts.push(`${skippedManual} manuell bearbeitete übersprungen`); return { updated, skippedManual, total: pending.length, message: `${parts.join(", ")}.` };
}) };
