import { TRPCError } from "@trpc/server";
import { and, eq } from "drizzle-orm";
import { z } from "zod";
import { bankAccounts, bankTransactions } from "../drizzle/schema";
import { deleteJournalEntry, getDb, revertBankTransaction, updateBankTransaction, upsertBookingRule } from "./db";
import { logger } from "./_core/logger";
import { orgProcedure } from "./_core/trpc";

export const bankImportStatusProcedures = {
  ignoreTransaction: orgProcedure.input(z.object({ transactionId: z.number() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await db.update(bankTransactions).set({ status: "ignored" }).where(and(eq(bankTransactions.id, input.transactionId), eq(bankTransactions.organizationId, ctx.organizationId))); return { success: true }; }),
  unapproveTransaction: orgProcedure.input(z.object({ transactionId: z.number() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const [tx] = await db.select().from(bankTransactions).where(and(eq(bankTransactions.id, input.transactionId), eq(bankTransactions.organizationId, ctx.organizationId))).limit(1); if (!tx) throw new TRPCError({ code: "NOT_FOUND" }); if (tx.status !== "matched") throw new TRPCError({ code: "BAD_REQUEST", message: "Transaktion ist nicht verbucht" }); if (tx.journalEntryId) await deleteJournalEntry(tx.journalEntryId); await revertBankTransaction(input.transactionId); return { success: true }; }),
  updateTransaction: orgProcedure.input(z.object({ transactionId: z.number(), description: z.string().optional(), counterparty: z.string().optional(), counterpartyIban: z.string().optional(), reference: z.string().optional(), suggestedDebitAccountId: z.number().nullable().optional(), suggestedCreditAccountId: z.number().nullable().optional(), aiReasoning: z.string().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const { transactionId, ...data } = input; const [tx] = await db.select().from(bankTransactions).where(and(eq(bankTransactions.id, transactionId), eq(bankTransactions.organizationId, ctx.organizationId))).limit(1); if (!tx) throw new TRPCError({ code: "NOT_FOUND" }); await updateBankTransaction(transactionId, { ...data, manuallyEdited: true }); if (tx.counterparty) try { const ids = (await db.select({ accountId: bankAccounts.accountId }).from(bankAccounts).where(eq(bankAccounts.organizationId, ctx.organizationId))).map(a => a.accountId); const rule: Parameters<typeof upsertBookingRule>[0] = { organizationId: ctx.organizationId, counterpartyPattern: tx.counterparty.trim(), bookingTextTemplate: data.description }; if (data.suggestedDebitAccountId && !ids.includes(data.suggestedDebitAccountId)) rule.debitAccountId = data.suggestedDebitAccountId; if (data.suggestedCreditAccountId && !ids.includes(data.suggestedCreditAccountId)) rule.creditAccountId = data.suggestedCreditAccountId; if (rule.bookingTextTemplate || rule.debitAccountId || rule.creditAccountId) await upsertBookingRule(rule); } catch (err) { logger.error({ err, transactionId }, "Failed to learn booking rule from transaction edit"); } return { success: true }; }),
};
