import { TRPCError } from "@trpc/server";
import { and, desc, eq, inArray, isNull, like, or } from "drizzle-orm";
import { z } from "zod";
import { bankAccounts, bankTransactions } from "../drizzle/schema";
import { getAllAccounts, getAllBookingRules, getDb } from "./db";
import { orgProcedure } from "./_core/trpc";

export const bankImportListingProcedures = {
  listRules: orgProcedure.query(async ({ ctx }) => { const rules = await getAllBookingRules(ctx.organizationId); const accounts = await getAllAccounts(ctx.organizationId); return rules.map(rule => ({ ...rule, debitAccountName: accounts.find(a => a.id === rule.debitAccountId)?.name, debitAccountNumber: accounts.find(a => a.id === rule.debitAccountId)?.number, creditAccountName: accounts.find(a => a.id === rule.creditAccountId)?.name, creditAccountNumber: accounts.find(a => a.id === rule.creditAccountId)?.number })); }),
  listUnmatchedTransactions: orgProcedure.input(z.object({ search: z.string().optional(), limit: z.number().default(50) })).query(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const conditions = [eq(bankTransactions.organizationId, ctx.organizationId), eq(bankTransactions.status, "pending"), or(isNull(bankTransactions.matchedDocumentId), eq(bankTransactions.matchedDocumentId, 0))]; if (input.search) { const q = `%${input.search}%`; conditions.push(or(like(bankTransactions.suggestedBookingText, q), like(bankTransactions.counterparty, q), like(bankTransactions.description, q))!); } const rows = await db.select({ id: bankTransactions.id, transactionDate: bankTransactions.transactionDate, bookingText: bankTransactions.suggestedBookingText, description: bankTransactions.description, amount: bankTransactions.amount, counterparty: bankTransactions.counterparty, bankAccountId: bankTransactions.bankAccountId }).from(bankTransactions).where(and(...conditions)).orderBy(desc(bankTransactions.transactionDate)).limit(input.limit); const ids = Array.from(new Set(rows.map(r => r.bankAccountId).filter(Boolean))) as number[]; const bankMap = ids.length ? Object.fromEntries((await db.select({ id: bankAccounts.id, name: bankAccounts.name }).from(bankAccounts).where(and(eq(bankAccounts.organizationId, ctx.organizationId), inArray(bankAccounts.id, ids)))).map(bank => [bank.id, bank.name])) : {}; return rows.map(row => ({ ...row, counterpartyName: row.counterparty ?? "", bankAccountName: row.bankAccountId ? bankMap[row.bankAccountId] ?? "" : "" })); }),
};
