export type VatEstvExportInput = { uid: string; organisationName: string; year: number; period: string; startDate: string; endDate: string; vatMethod: "effective" | "saldo"; turnover81: string | number; turnover26: string | number; turnover38: string | number; vatDue81: string | number; vatDue26: string | number; vatDue38: string | number; inputTax: string | number; netVatPayable: string | number };

const escape = (value: string | number) => `"${String(value).replaceAll('"', '""')}"`;
const amount = (value: string | number) => Number(value || 0).toFixed(2);

export function buildEstvVatCsv(input: VatEstvExportInput) {
  const rows: Array<[string, string | number]> = [
    ["Format", "eCH-0217-Vorbereitung CSV"], ["UID", input.uid], ["Organisation", input.organisationName], ["Steuerperiode", `${input.period} ${input.year}`], ["Periode von", input.startDate], ["Periode bis", input.endDate], ["Abrechnungsmethode", input.vatMethod],
    ["Ziffer 302 Umsatz Normalsatz 8.1%", amount(input.turnover81)], ["Ziffer 303 Umsatz Sondersatz 2.6%", amount(input.turnover26)], ["Ziffer 304 Umsatz Reduzierter Satz 3.8%", amount(input.turnover38)], ["MWST Normalsatz", amount(input.vatDue81)], ["MWST Sondersatz", amount(input.vatDue26)], ["MWST Reduzierter Satz", amount(input.vatDue38)], ["Ziffer 400 Vorsteuer", amount(input.inputTax)], ["Ziffer 500 / 510 Zahllast oder Guthaben", amount(input.netVatPayable)],
  ];
  return `ESTV MWST-Abrechnung;Wert\n${rows.map(([label, value]) => `${escape(label)};${escape(value)}`).join("\n")}\n`;
}

const xmlEscape = (value: string | number) => String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&apos;");

export function buildEch0217EffectiveXmlDraft(input: VatEstvExportInput & { businessReferenceId: string; formOfReporting: 1 | 2; generatedAt: string; applicationManufacturer: string; applicationProduct: string; applicationVersion: string }) {
  if (input.vatMethod !== "effective") throw new Error("Der XML-Entwurf unterstützt derzeit nur die effektive Methode.");
  const tag = (name: string, value: string | number) => `    <${name}>${xmlEscape(value)}</${name}>`;
  const supplies = [["8.1", input.turnover81], ["2.6", input.turnover26], ["3.8", input.turnover38]].filter(([, value]) => Number(value) !== 0).map(([rate, value]) => `    <suppliesPerTaxRate>\n${tag("taxRate", rate)}\n${tag("turnover", amount(value))}\n    </suppliesPerTaxRate>`).join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>\n<!-- eCH-0217:2025 XML-Entwurf; vor ESTV-Upload gegen vollständigen XSD-Satz validieren. -->\n<VATDeclaration xmlns="http://www.ech.ch/xmlns/eCH-0217/2" xmlns:eCH-0058="http://www.ech.ch/xmlns/eCH-0058/5">\n  <generalInformation>\n${tag("uid", input.uid)}\n${tag("organisationName", input.organisationName)}\n${tag("generationTime", input.generatedAt)}\n${tag("reportingPeriodFrom", input.startDate)}\n${tag("reportingPeriodTill", input.endDate)}\n${tag("typeOfSubmission", 1)}\n${tag("formOfReporting", input.formOfReporting)}\n${tag("businessReferenceId", input.businessReferenceId)}\n    <sendingApplication>\n${tag("eCH-0058:manufacturer", input.applicationManufacturer)}\n${tag("eCH-0058:product", input.applicationProduct)}\n${tag("eCH-0058:productVersion", input.applicationVersion)}\n    </sendingApplication>\n  </generalInformation>\n  <turnoverComputation>\n${tag("totalConsideration", amount(Number(input.turnover81) + Number(input.turnover26) + Number(input.turnover38)))}\n  </turnoverComputation>\n  <effectiveReportingMethod>\n${tag("grossOrNet", 1)}\n${supplies}\n${tag("inputTaxMaterialAndServices", amount(input.inputTax))}\n  </effectiveReportingMethod>\n${tag("payableTax", amount(input.netVatPayable))}\n</VATDeclaration>\n`;
}

export function buildEch0217NetTaxRateXmlDraft(input: Omit<VatEstvExportInput, "vatMethod" | "turnover81" | "turnover26" | "turnover38" | "vatDue81" | "vatDue26" | "vatDue38" | "inputTax"> & { businessReferenceId: string; formOfReporting: 1 | 2; generatedAt: string; applicationManufacturer: string; applicationProduct: string; applicationVersion: string; supplies: Array<{ taxRate: string | number; turnover: string | number }> }) {
  if (!input.supplies.length) throw new Error("Mindestens ein bewilligter Saldosteuersatz ist erforderlich.");
  const tag = (name: string, value: string | number) => `    <${name}>${xmlEscape(value)}</${name}>`;
  const supplies = input.supplies.map(({ taxRate, turnover }) => `    <suppliesPerTaxRate>\n${tag("taxRate", taxRate)}\n${tag("turnover", amount(turnover))}\n    </suppliesPerTaxRate>`).join("\n");
  const total = input.supplies.reduce((sum, item) => sum + Number(item.turnover), 0);
  return `<?xml version="1.0" encoding="UTF-8"?>\n<!-- eCH-0217:2025 XML-Entwurf; bewilligte Saldosteuersätze erforderlich. -->\n<VATDeclaration xmlns="http://www.ech.ch/xmlns/eCH-0217/2" xmlns:eCH-0058="http://www.ech.ch/xmlns/eCH-0058/5">\n  <generalInformation>\n${tag("uid", input.uid)}\n${tag("organisationName", input.organisationName)}\n${tag("generationTime", input.generatedAt)}\n${tag("reportingPeriodFrom", input.startDate)}\n${tag("reportingPeriodTill", input.endDate)}\n${tag("typeOfSubmission", 1)}\n${tag("formOfReporting", input.formOfReporting)}\n${tag("businessReferenceId", input.businessReferenceId)}\n    <sendingApplication>\n${tag("eCH-0058:manufacturer", input.applicationManufacturer)}\n${tag("eCH-0058:product", input.applicationProduct)}\n${tag("eCH-0058:productVersion", input.applicationVersion)}\n    </sendingApplication>\n  </generalInformation>\n  <turnoverComputation>\n${tag("totalConsideration", amount(total))}\n  </turnoverComputation>\n  <netTaxRateMethod>\n${supplies}\n  </netTaxRateMethod>\n${tag("payableTax", amount(input.netVatPayable))}\n</VATDeclaration>\n`;
}

export function buildEch0217FlatTaxRateXmlDraft(input: Omit<VatEstvExportInput, "vatMethod" | "turnover81" | "turnover26" | "turnover38" | "vatDue81" | "vatDue26" | "vatDue38" | "inputTax"> & { businessReferenceId: string; formOfReporting: 1 | 2; generatedAt: string; applicationManufacturer: string; applicationProduct: string; applicationVersion: string; activity: string; taxRate: string | number; turnover: string | number }) {
  if (!input.activity.trim()) throw new Error("Eine bewilligte Tätigkeit ist für die Pauschalsteuersatzmethode erforderlich.");
  const tag = (name: string, value: string | number) => `    <${name}>${xmlEscape(value)}</${name}>`;
  return `<?xml version="1.0" encoding="UTF-8"?>\n<!-- eCH-0217:2025 XML-Entwurf; bewilligte Tätigkeit und Pauschalsteuersatz erforderlich. -->\n<VATDeclaration xmlns="http://www.ech.ch/xmlns/eCH-0217/2" xmlns:eCH-0058="http://www.ech.ch/xmlns/eCH-0058/5">\n  <generalInformation>\n${tag("uid", input.uid)}\n${tag("organisationName", input.organisationName)}\n${tag("generationTime", input.generatedAt)}\n${tag("reportingPeriodFrom", input.startDate)}\n${tag("reportingPeriodTill", input.endDate)}\n${tag("typeOfSubmission", 1)}\n${tag("formOfReporting", input.formOfReporting)}\n${tag("businessReferenceId", input.businessReferenceId)}\n    <sendingApplication>\n${tag("eCH-0058:manufacturer", input.applicationManufacturer)}\n${tag("eCH-0058:product", input.applicationProduct)}\n${tag("eCH-0058:productVersion", input.applicationVersion)}\n    </sendingApplication>\n  </generalInformation>\n  <turnoverComputation>\n${tag("totalConsideration", amount(input.turnover))}\n  </turnoverComputation>\n  <flatTaxRateMethod>\n    <suppliesPerTaxRate>\n${tag("activity", input.activity)}\n${tag("taxRate", input.taxRate)}\n${tag("turnover", amount(input.turnover))}\n    </suppliesPerTaxRate>\n  </flatTaxRateMethod>\n${tag("payableTax", amount(input.netVatPayable))}\n</VATDeclaration>\n`;
}
