import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Pencil, Plus, Trash2 } from "lucide-react";

export function CustomersList({ customers, onEdit, onDeactivate, onAddService, onEditService, onDeactivateService }: { customers: any[]; onEdit: (customer: any) => void; onDeactivate: (customer: any) => void; onAddService: (customerId: number) => void; onEditService: (service: any, customerId: number) => void; onDeactivateService: (service: any) => void }) {
  if (customers.length === 0) return <Card><CardContent className="py-10 text-center text-muted-foreground">Keine Kunden gefunden.</CardContent></Card>;
  return <div className="space-y-3">{customers.map(customer => <Card key={customer.id}><CardContent className="py-4"><div className="flex justify-between gap-4"><div><div className="flex items-center gap-2"><span className="font-semibold">{customer.name}</span>{customer.company && <span className="text-sm text-muted-foreground">{customer.company}</span>}{!customer.isActive && <Badge variant="secondary">Inaktiv</Badge>}</div><p className="text-sm text-muted-foreground">{[customer.street, customer.zipCode, customer.city].filter(Boolean).join(", ")}</p><p className="text-xs text-muted-foreground">{[customer.email, customer.phone].filter(Boolean).join(" · ")}</p></div><div className="flex gap-1"><Button size="icon" variant="ghost" onClick={() => onEdit(customer)}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" onClick={() => onDeactivate(customer)}><Trash2 className="h-4 w-4" /></Button></div></div><div className="mt-3 border-t pt-3"><div className="flex justify-between items-center mb-2"><span className="text-sm font-medium">Dienstleistungen</span><Button size="sm" variant="outline" onClick={() => onAddService(customer.id)}><Plus className="h-3 w-3 mr-1" />Hinzufügen</Button></div>{(customer.services || []).map((service: any) => <div key={service.id} className="flex justify-between text-sm py-1"><span>{service.description}{service.isDefault && <Badge className="ml-2" variant="secondary">Primär</Badge>}</span><span className="flex gap-2 items-center text-muted-foreground">{service.revenueAccount?.number} {service.hourlyRate && `${service.hourlyRate} CHF/h`}<Button size="icon" variant="ghost" className="h-6 w-6" onClick={() => onEditService(service, customer.id)}><Pencil className="h-3 w-3" /></Button><Button size="icon" variant="ghost" className="h-6 w-6" onClick={() => onDeactivateService(service)}><Trash2 className="h-3 w-3" /></Button></span></div>)}</div></CardContent></Card>)}</div>;
}
