import { CalendarClock, Pause, Play, Plus, RefreshCw } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

type Template = { id: number; subject: string; amount: string; currency: string; interval: "monthly" | "quarterly" | "yearly"; nextRunDate: string; isActive: boolean };
const intervalLabel = { monthly: "Monatlich", quarterly: "Quartalsweise", yearly: "Jährlich" };

export function RecurringInvoicesPanel({ templates, onToggle, onRunDue, onCreate, isUpdating, isRunning }: { templates: Template[]; onToggle: (template: Template) => void; onRunDue: () => void; onCreate: () => void; isUpdating: boolean; isRunning: boolean }) {
  return <Card><CardHeader className="pb-3 flex-row items-center justify-between"><CardTitle className="text-base flex items-center gap-2"><CalendarClock className="h-4 w-4" /> Wiederkehrende Rechnungen</CardTitle><div className="flex gap-2"><Button variant="outline" size="sm" className="gap-1" onClick={onCreate}><Plus className="h-3.5 w-3.5" />Vorlage</Button><Button variant="outline" size="sm" className="gap-1" disabled={isRunning} onClick={onRunDue}><RefreshCw className={`h-3.5 w-3.5 ${isRunning ? "animate-spin" : ""}`} />Fällige ausführen</Button></div></CardHeader><CardContent>{templates.length === 0 ? <p className="text-sm text-muted-foreground">Noch keine wiederkehrenden Rechnungsvorlagen erfasst.</p> : <div className="space-y-2">{templates.map(template => <div key={template.id} className="flex flex-wrap items-center justify-between gap-3 rounded-md border p-3"><div><div className="font-medium text-sm">{template.subject}</div><div className="text-xs text-muted-foreground">{intervalLabel[template.interval]} · Nächste Ausführung: {template.nextRunDate} · {new Intl.NumberFormat("de-CH", { style: "currency", currency: template.currency }).format(Number(template.amount))}</div></div><div className="flex items-center gap-2"><Badge variant={template.isActive ? "default" : "outline"}>{template.isActive ? "Aktiv" : "Pausiert"}</Badge><Button variant="outline" size="sm" className="gap-1" disabled={isUpdating} onClick={() => onToggle(template)}>{template.isActive ? <Pause className="h-3.5 w-3.5" /> : <Play className="h-3.5 w-3.5" />}{template.isActive ? "Pausieren" : "Aktivieren"}</Button></div></div>)}</div>}</CardContent></Card>;
}
