import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";

type Customer = { id: number; name: string; company?: string | null };
export type RecurringInvoiceInput = { customerId: number; subject: string; amount: number; interval: "monthly" | "quarterly" | "yearly"; nextRunDate: string; paymentTermDays: number };

export function RecurringInvoiceCreateDialog({ open, onOpenChange, customers, onCreate, isPending }: { open: boolean; onOpenChange: (open: boolean) => void; customers: Customer[]; onCreate: (input: RecurringInvoiceInput) => void; isPending: boolean }) {
  const [customerId, setCustomerId] = useState(""); const [subject, setSubject] = useState(""); const [amount, setAmount] = useState(""); const [interval, setInterval] = useState<RecurringInvoiceInput["interval"]>("monthly"); const [nextRunDate, setNextRunDate] = useState(() => new Date().toISOString().slice(0, 10)); const [paymentTermDays, setPaymentTermDays] = useState("30");
  const submit = () => { const numericAmount = Number(amount); if (!customerId || !subject.trim() || !Number.isFinite(numericAmount) || numericAmount <= 0) return; onCreate({ customerId: Number(customerId), subject: subject.trim(), amount: numericAmount, interval, nextRunDate, paymentTermDays: Number(paymentTermDays) || 30 }); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Wiederkehrende Rechnungsvorlage</DialogTitle></DialogHeader><div className="grid gap-3 py-2"><label className="grid gap-1 text-sm font-medium">Kunde<select className="h-9 rounded-md border bg-background px-3" value={customerId} onChange={event => setCustomerId(event.target.value)}><option value="">Kunden auswählen</option>{customers.map(customer => <option key={customer.id} value={customer.id}>{customer.company || customer.name}</option>)}</select></label><label className="grid gap-1 text-sm font-medium">Betreff<Input value={subject} onChange={event => setSubject(event.target.value)} /></label><label className="grid gap-1 text-sm font-medium">Betrag (CHF)<Input type="number" min="0.01" step="0.01" value={amount} onChange={event => setAmount(event.target.value)} /></label><label className="grid gap-1 text-sm font-medium">Intervall<select className="h-9 rounded-md border bg-background px-3" value={interval} onChange={event => setInterval(event.target.value as RecurringInvoiceInput["interval"])}><option value="monthly">Monatlich</option><option value="quarterly">Quartalsweise</option><option value="yearly">Jährlich</option></select></label><label className="grid gap-1 text-sm font-medium">Nächste Ausführung<Input type="date" value={nextRunDate} onChange={event => setNextRunDate(event.target.value)} /></label><label className="grid gap-1 text-sm font-medium">Zahlungsfrist (Tage)<Input type="number" min="1" value={paymentTermDays} onChange={event => setPaymentTermDays(event.target.value)} /></label></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Abbrechen</Button><Button disabled={isPending} onClick={submit}>Vorlage speichern</Button></DialogFooter></DialogContent></Dialog>;
}
