import { Pencil, Trash2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

export function SuppliersList({ suppliers, onEdit, onDeactivate }: { suppliers: any[]; onEdit: (supplier: any) => void; onDeactivate: (supplier: any) => void }) {
  return <Card><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Name</TableHead><TableHead>Adresse</TableHead><TableHead>IBAN</TableHead><TableHead>Zahlungsfrist</TableHead><TableHead>Aufwandkonto</TableHead><TableHead>Kontakt</TableHead><TableHead className="w-[100px]">Aktionen</TableHead></TableRow></TableHeader><TableBody>{suppliers.length === 0 ? <TableRow><TableCell colSpan={7} className="text-center py-8 text-muted-foreground">Keine Lieferanten erfasst</TableCell></TableRow> : suppliers.map(supplier => <TableRow key={supplier.id} className={!supplier.isActive ? "opacity-50" : ""}><TableCell className="font-medium">{supplier.name}{!supplier.isActive && <Badge variant="secondary" className="ml-2 text-xs">Inaktiv</Badge>}{supplier.notes === "Automatisch aus Rechnung erstellt" && <Badge variant="outline" className="ml-2 text-xs text-blue-600 border-blue-300">Auto</Badge>}</TableCell><TableCell className="text-sm text-muted-foreground">{[supplier.street, [supplier.zipCode, supplier.city].filter(Boolean).join(" ")].filter(Boolean).join(", ")}</TableCell><TableCell className="text-sm font-mono">{supplier.iban ? supplier.iban.replace(/(.{4})/g, "$1 ").trim() : <span className="text-orange-500 text-xs">Keine IBAN</span>}</TableCell><TableCell className="text-sm">{supplier.paymentTermDays} Tage</TableCell><TableCell className="text-sm">{supplier.defaultDebitAccount ? `${supplier.defaultDebitAccount.number} ${supplier.defaultDebitAccount.name}` : <span className="text-muted-foreground">–</span>}</TableCell><TableCell className="text-sm text-muted-foreground">{supplier.contactPerson || supplier.email || supplier.phone || "–"}</TableCell><TableCell><div className="flex gap-1"><Button size="icon" variant="ghost" onClick={() => onEdit(supplier)}><Pencil className="h-4 w-4" /></Button>{supplier.isActive && <Button size="icon" variant="ghost" className="text-destructive" onClick={() => onDeactivate(supplier)}><Trash2 className="h-4 w-4" /></Button>}</div></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>;
}
